// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXwQVnwSqXAQeVvXzRcxoBKjGGgeUaX44',
    appId: '1:900179340437:web:930b4ea6734d22ddc0bf9c',
    messagingSenderId: '900179340437',
    projectId: 'learning-app-947a8',
    authDomain: 'learning-app-947a8.firebaseapp.com',
    storageBucket: 'learning-app-947a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdzrrGN5W9d6J4DxwvP1eMDf78s4o-EZc',
    appId: '1:900179340437:android:179677d4b5efc587c0bf9c',
    messagingSenderId: '900179340437',
    projectId: 'learning-app-947a8',
    storageBucket: 'learning-app-947a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIlyyVG3Ue3XXHec31VWx3aWKq2DkJZNQ',
    appId: '1:900179340437:ios:2e10cc851d208161c0bf9c',
    messagingSenderId: '900179340437',
    projectId: 'learning-app-947a8',
    storageBucket: 'learning-app-947a8.appspot.com',
    iosBundleId: 'com.example.languageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIlyyVG3Ue3XXHec31VWx3aWKq2DkJZNQ',
    appId: '1:900179340437:ios:026a9e3b29bb9c83c0bf9c',
    messagingSenderId: '900179340437',
    projectId: 'learning-app-947a8',
    storageBucket: 'learning-app-947a8.appspot.com',
    iosBundleId: 'com.example.languageApp.RunnerTests',
  );
}
